# 2 Numpy

## 2.1 Creation

In [1]:
import numpy as np # import numpy module as np

matrix = np.array([np.arange(3), [i for i in range(3,6)], [6,7,8]])
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 2.2 Initialization

In [2]:
np.zeros([4,5,6])

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [3]:
np.ones([3,4], dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.arange(1,10,1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [6]:
np.full([3,3], 4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 2.3 Copying, Sorting, Slicing

In [8]:
np.copy(matrix)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
matrix.copy()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
matrix.view()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
matrix.sort()

In [12]:
matrix.sort(axis=1)

In [13]:
matrix[0:,:1]

array([[0],
       [3],
       [6]])

In [14]:
matrix[:2, 1:]

array([[1, 2],
       [4, 5]])

In [15]:
matrix[:2, :]

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
matrix[1,0]

3

In [17]:
matrix[0] = 42

In [18]:
matrix[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [19]:
# matrix[] this command gives a syntax error

In [20]:
matrix[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [21]:
matrix[1:100]

array([[3, 4, 5],
       [6, 7, 8]])

In [22]:
matrix[:]

array([[42, 42, 42],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [23]:
matrix[1:,:2]

array([[3, 4],
       [6, 7]])

In [24]:
matrix[:2, 1:]

array([[42, 42],
       [ 4,  5]])

In [25]:
matrix.ravel() #Return a contiguous flattened array.

array([42, 42, 42,  3,  4,  5,  6,  7,  8])

In [26]:
matrix[:,1].copy()

array([42,  4,  7])

In [27]:
matrix[1].tolist()

[3, 4, 5]

In [28]:
matrix.reshape(-1)

array([42, 42, 42,  3,  4,  5,  6,  7,  8])

## 2.4 Apply elements wise operations and functions of NumPy
### 2.4.1 Try Out

In [29]:
np.sqrt(matrix)

array([[6.4807407 , 6.4807407 , 6.4807407 ],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [30]:
np.exp(matrix)

array([[1.73927494e+18, 1.73927494e+18, 1.73927494e+18],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [31]:
np.min(np.maximum(np.random.randn(6), np.random.randn(6)))

-0.01897005020707411

In [32]:
np.mean(matrix)

17.666666666666668

In [33]:
np.mean(matrix , axis=0)

array([17.        , 17.66666667, 18.33333333])

In [34]:
np.sum(matrix)

159

In [35]:
np.invert(matrix)

array([[-43, -43, -43],
       [ -4,  -5,  -6],
       [ -7,  -8,  -9]], dtype=int32)

In [36]:
np.random.randint(0, 1)

0

In [37]:
from numpy.random import randint

class RandomWalk1D:
    def __init__(self, max_steps):
        self.max_steps = max_steps

    def walk(self):
        random_numbers = randint(0, 2, size=self.max_steps)
        steps = np.where(random_numbers == 0, -1, +1)
        path = np.cumsum(steps)
        return path

random_walker1d = RandomWalk1D(500)
random_walker1d.walk()

array([-1,  0,  1,  2,  3,  2,  1,  2,  3,  2,  3,  2,  1,  0, -1,  0, -1,
       -2, -3, -2, -1,  0, -1, -2, -1, -2, -1,  0,  1,  2,  1,  0, -1,  0,
        1,  0,  1,  0, -1,  0,  1,  0,  1,  2,  3,  4,  5,  6,  5,  6,  5,
        6,  5,  6,  7,  8,  7,  8,  9,  8,  7,  8,  9, 10, 11, 12, 13, 12,
       13, 12, 11, 12, 13, 14, 15, 16, 15, 16, 15, 14, 15, 16, 15, 14, 15,
       14, 15, 14, 15, 16, 17, 18, 19, 20, 21, 20, 21, 22, 23, 22, 23, 22,
       23, 24, 23, 22, 23, 24, 23, 24, 23, 22, 21, 20, 21, 22, 23, 22, 21,
       22, 23, 24, 25, 24, 23, 22, 23, 24, 25, 26, 27, 26, 27, 28, 29, 30,
       31, 30, 29, 30, 31, 32, 31, 30, 29, 28, 27, 26, 27, 26, 25, 26, 25,
       24, 23, 24, 23, 24, 25, 24, 23, 24, 25, 24, 25, 26, 25, 24, 25, 24,
       25, 26, 27, 28, 29, 28, 29, 30, 29, 30, 31, 32, 31, 30, 29, 30, 29,
       28, 29, 28, 27, 26, 27, 28, 29, 28, 27, 28, 29, 28, 27, 28, 29, 30,
       29, 28, 27, 28, 27, 26, 25, 26, 25, 24, 23, 22, 23, 24, 25, 26, 25,
       26, 27, 26, 25, 26

In [51]:
class RandomWalk:
    def __init__(self, max_steps):
        self.max_steps = max_steps

    def walk(self):
        x = [0]
        y = [0]

        for j in range(self.max_steps - 1):
            step_x = randint(0,2)
            if step_x == 1:
                x.append(x[j] + 1)
            else:
                x.append(x[j] - 1)
    
            step_y = randint(0,2)
            if step_y == 1:
                y.append(y[j] + 1)
            else:
                y.append(y[j] - 1)
                
        return np.array(list(zip(x, y)))

random_walker = RandomWalk(500)
random_walker.walk()

array([[  0,   0],
       [  1,  -1],
       [  0,  -2],
       [  1,  -1],
       [  2,  -2],
       [  1,  -1],
       [  2,   0],
       [  1,  -1],
       [  0,   0],
       [  1,   1],
       [  2,   0],
       [  1,  -1],
       [  0,   0],
       [ -1,   1],
       [ -2,   2],
       [ -1,   3],
       [ -2,   2],
       [ -3,   3],
       [ -4,   2],
       [ -5,   3],
       [ -4,   2],
       [ -5,   3],
       [ -6,   2],
       [ -7,   3],
       [ -6,   4],
       [ -7,   5],
       [ -6,   4],
       [ -5,   5],
       [ -6,   6],
       [ -7,   5],
       [ -6,   4],
       [ -7,   5],
       [ -6,   6],
       [ -5,   5],
       [ -6,   6],
       [ -7,   7],
       [ -6,   8],
       [ -7,   7],
       [ -8,   6],
       [ -7,   7],
       [ -8,   8],
       [ -9,   7],
       [-10,   8],
       [ -9,   9],
       [-10,   8],
       [-11,   9],
       [-10,   8],
       [ -9,   7],
       [-10,   6],
       [ -9,   7],
       [-10,   8],
       [-11,   7],
       [-10,