In [13]:

import numpy as np
from sklearn import datasets
iris = datasets.load_iris() #iris data set is loaded
X = iris.data
Y = iris.target
#print(iris)

In [5]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB() # c l f i s a c l a s s i f i e r
clf.fit(X,Y)
print('Training Accuracy: ',clf.score(X,Y)) # T r a i n i n g a c c u r a c y

Training Accuracy:  0.96


In [17]:
print(X)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [16]:
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [3]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB() # c l f i s a c l a s s i f i e r .
clf.fit(X,Y)
print('Training Accuracy: ',clf.score(X,Y)) # T r a i n i n g a c c u r a c y


Training Accuracy:  0.9533333333333334


In [5]:
from sklearn import neighbors , datasets
clf = neighbors.KNeighborsClassifier(n_neighbors =1) # 1􀀀Ne a r e s t Ne ighbor
clf.fit(X,Y) # Model
print('Training Accuracy: ',clf.score(X,Y)) # T r a i n i n g a c c u r a c y

Training Accuracy:  1.0


In [7]:
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1,gamma=1).fit(X, Y) # c l f i s a c l a s s i f i e r
clf.fit(X,Y) # Model
print('Training Accuracy: ',clf.score(X,Y)) # T r a i n i n g a c c u r a c y

Training Accuracy:  0.9933333333333333


In [8]:
# s p l i t  d a t a  as  2 / 3  f o r  t r a i n i n g  and   1 / 3 f o r t e s t i n g
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size =0.333,random_state =0)
clf.fit(X_train ,Y_train) # c l f i s a c l a s s i f i e r .
print('Test Accuracy: ',clf.score(X_test ,Y_test )) # T e s t a c c u r a c y

Test Accuracy:  0.98


In [9]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, Y, cv=10) # 10 - f o l d c r o s s v a l i d a t i o n
print(scores) # R e s u l t s  f o r  a l l  t h e  f o l d s
print("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

[1.         0.93333333 1.         1.         0.86666667 1.
 0.93333333 1.         1.         1.        ]
10CV Accuracy: 0.97 (+/- 0.09)


In [10]:
from sklearn.metrics import confusion_matrix
Y_pred = clf.fit(X_train , Y_train ).predict(X_test)
print(confusion_matrix(Y_test , Y_pred ))

[[16  0  0]
 [ 0 18  1]
 [ 0  0 15]]


In [11]:
from sklearn.metrics import classification_report
target_names =['setosa', 'versicolor', 'virginica'] # p r o v i d e c l a s s l a b e l s
print(classification_report(Y_test , Y_pred , target_names=target_names ))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       1.00      0.95      0.97        19
  virginica       0.94      1.00      0.97        15

avg / total       0.98      0.98      0.98        50



In [6]:
from sklearn import tree
X = [[140, 1],[130, 1], [150, 0], [170, 0]]
Y = [1, 2, 3, 4]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)
clf.predict([[170,1]])
clf.predict_proba ([[170,1]])

array([[1., 0., 0., 0.]])